### ISSUE TITLE
Adding "Send Invitation" action to the search sharees control

### ISSUE THREAD

**Issue by shokri-navid** [shokri-navid/OCM-1.1#1]
inside the sender panel when the user types an email in the search box like below:

 
![image](https://github.com/user-attachments/assets/a0175a8f-838c-44df-b1a6-1a5c3eaa666f)
 we must add another option below the email share link to enable user to sent invitation link to the recipient.

**Comment by shokri-navid** [comment]
I found that the API call for searching sharees is: 

>	/ocs/v2.php/apps/files_sharing/api/v1/sharees

and the code is: 

https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/apps/files_sharing/lib/Controller/ShareesAPIController.php#L104

**Comment by shokri-navid** [comment]
So, It seems We should add another Share Type in IShare file: 
 
https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/lib/public/Share/IShare.php#L102

So I decided to add this type there: 

`	public const TYPE_INVITATION_LINK = 16;`

**Comment by shokri-navid** [comment]
in calling the API this flow is executed: 

1- https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/apps/files_sharing/lib/Controller/ShareesAPIController.php#L104

2- https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/lib/private/Share20/Manager.php#L1863

3- https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/lib/private/Share20/ProviderFactory.php#L309

we should decide whether need to register a new ShareProvider class or create a new one that is inherited from ShareByMailProvider class?

**Comment by shokri-navid** [comment]
So it seems we should create our own share provider like ShareByEmailInvitationProvider.
I looked into ShareByMailProvider there: 
https://github.com/SUNET/nextcloud-server/blob/master/apps/sharebymail/lib/ShareByMailProvider.php

and it has a specific template engine and data access layer inside the class code. 

:eyes: 
I guess we should create our own application like **shareByInvitationCode** to put our db migrations and required helper classes there

**Comment by michielbdejong** [comment]
> we must add another option below the email share link

No, I don't think so. I think you can just edit the email template so that the email message _includes_ the invite link.

**Comment by shokri-navid** [comment]
So, does it mean we want to override the functionality of sharing files using email? When we create another application based on my suggestion we can have another extra option in this screenshot and the user can send the Nextcloud sharing link and Nextcloud invitation link meanwhile. 

but if we change the ShareByEmail application user can only share the file using the invitation link :thinking: 
It seems we should create our database tables to store and retrieve the invitation link and it can be done inside our application. or we should apply some modifications to the table that belongs to email sharing and use it for our use case?

**Comment by shokri-navid** [comment]
I reviewed the ShareByMailProvider and accoording to this code: 

https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/apps/sharebymail/lib/ShareByMailProvider.php#L670

this invitation could be stored inside the `share` table of the inviter instance of Nextcloud.
but the type of share is hard-coded based on this line:

https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/apps/sharebymail/lib/ShareByMailProvider.php#L690

**Comment by shokri-navid** [comment]
Base on my new code review It seems I should check the sharing process and if we can add another flag to indicate the request is invitation link or email sharing then we can go advance with the `shareBymail` application.

**Comment by shokri-navid** [comment]
So, Based on this flow: 

https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/apps/files_sharing/lib/Controller/ShareAPIController.php#L535
https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/apps/files_sharing/lib/Controller/ShareAPIController.php#L785
https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/lib/private/Share20/Manager.php#L620
https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/lib/private/Share20/Manager.php#L715

It seems that we could change the mail_sharing app

**Comment by michielbdejong** [comment]
It's an interesting product question; when trying to share a document with someone whose email address you have, do you want to send them an email containing a public link, an email containing an OCM invite, or an email containing both these things?

I understand your initial approach of creating a separate dialog for invite generation without public link generation, and maybe we should have that too, but baking it into the public-link-email flow that people already use makes it (I think) much nicer to use.

It also ties in with @glpatcern's work 'webapp' protocol, so there are three related work flows:

* Alice gestures to share a document with Bob, who is not yet in her OCM contacts, but she does have his email address bob@bob.com
* Alice's server sends an email to bob@bob.com, containing a public link for the document as well as an OCM invite
* If Bob has a web browser, he can access the document on http://alice.com/public/link
* If Bob additionally has an account at an OCM server, he can paste the `ocm-invite://blablabla@alice.com` into it, so:
  * It will make Alice show up as a contact.
  * Bob will now also show up in Alice's contacts.
  * And the document will show up as a webdav mount for Bob.
  * And Bob could have an additional option there 'visit on source server' which would take him to the public link view again! :)

**Comment by michielbdejong** [comment]
@shokri-navid see https://matrix.to/#/!gdbuoUSzyimkuwibvC:gitter.im/$3RJHMm3C-5rlkvK7zKwzi-ybfNqhU-GGMd9jJuEMy5A?via=gitter.im&via=matrix.org&via=matrix.azadehafzar.ir

**Comment by shokri-navid** [comment]
accourding to this line of code : 

https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/apps/files_sharing/lib/Controller/ShareesAPIController.php#L192C3-L192C126

there is function in this permalink that should be change to show our desired result: 

https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/lib/private/Collaboration/Collaborators/Search.php#L30

**Comment by shokri-navid** [comment]
it seems there should be another CollabratorPlugin or we should make some change on MailSearchPlugin to show the result accourding to this line of code: 

https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/lib/private/Collaboration/Collaborators/Search.php#L39
 
 the value of the `$this->pluginList` is like this: 
 
`array ( 0 => array ( 0 => 'OC\\Collaboration\\Collaborators\\UserPlugin', ), 1 => array ( 0 => 'OC\\Collaboration\\Collaborators\\GroupPlugin', ), 4 => array ( 0 => 'OC\\Collaboration\\Collaborators\\MailPlugin', ), 6 => array ( 0 => 'OC\\Collaboration\\Collaborators\\RemotePlugin', ), 9 => array ( 0 => 'OC\\Collaboration\\Collaborators\\RemoteGroupPlugin', ), )`

**Comment by shokri-navid** [comment]
So it seems I had a victory :tada: 
and with this commit I have share with type 16 //INVITATION_LINK in ShareesApi Response. 

https://github.com/SUNET/nextcloud-server/commit/d8e2743fa5d52d079c80bd074115da8460dd4936

but the lable and name are still empty and I should find the reason.

**Comment by shokri-navid** [comment]
So it seems the back-end code is finished. but I learned that the Front side should be updated because when I am searching for a contact to share the file a request is generated on front-end side like this: 
> https://nextcloud1.docker/ocs/v2.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&search=navid.pdp11@gmail.com&lookup=false&perPage=25&shareType[]=0,1,6,9,7,10,8,12,4
 
Obviously, sharetype (16 ) is not included in the request. and this is the reason for the absence of share type 16 in the link header in the response: 

> https://github.com/SUNET/nextcloud-server/blob/aec5edc05bf855e3e112b01f1335e70a89d1f841/apps/files_sharing/lib/Controller/ShareesAPIController.php#L174

So, I will close this Issue and create another for changing the frontend code:

https://github.com/shokri-navid/OCM-1.1/issues/4
